# Extend from the Microsoft Python dev container image
FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

# Install the Docker CLI to allow Docker commands to be run inside the container
RUN apt-get update \
    && apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
    && apt-get update \
    && apt-get install -y docker-ce-cli
